### ISSUE TITLE
 Runtime Analysis

### ISSUE THREAD

**Issue by Wu-ZW** [sair-lab/AirSLAM#108]
when I run euroc datasets, some parameters as follows: image size is set 640*480, superpoint max_keypoints is set 200,
![image](https://github.com/sair-lab/AirVO/assets/81010472/826011e5-7268-4b70-a0fc-a3d4557d6c84)
the time of detecting and tracking feature points for one image is about 92 ms, more than 65 ms in paper. Is any parameters i need to adjust?

**Comment by Wu-ZW** [comment]
l used Orin NX (16GB) edition.

**Comment by xukuanHIT** [comment]
@Wu-ZW HI, we run on the  Nvidia Jetson AGX Xavier for runtime analysis. The computing capability of Jetson AGX Xavier is better than your  Orin NX.

**Comment by Wu-ZW** [comment]
thanks for your replay! emmm,  the computing capability of jeston orin nx (8.7) is larger than AGX Xavier(7.2).
![image](https://github.com/sair-lab/AirVO/assets/81010472/6a2cea62-f6e0-4300-9c3f-f87597c629f6)

**Comment by xukuanHIT** [comment]
Sorry for my mistake. The comparison can be found [here](https://developer.nvidia.com/embedded/jetson-modules#:~:text=TX2%20NX-,AI%20Performance,-275%20TOPS), but it is true that jeston orin nx is  more powerful than AGX Xavier. 
Can you tell me your version of TensorRT? and have you tried the original Python version of superpoint and superglue on your jeston orin nx?

**Comment by Wu-ZW** [comment]
I have run original code of sp and  sg using PyTorch-CUDA, it is Inefficient.
the consumption of point extraction and point matching is unstable, 
the parameters as follow:
![image](https://github.com/sair-lab/AirVO/assets/81010472/886eabe1-5778-407b-ac76-a7634c3d7b47)
tensorrt + CUDA ....version as follows:
![image](https://github.com/sair-lab/AirVO/assets/81010472/bfa9520d-e403-42bf-b49d-61d6c9513dff)

**Comment by xukuanHIT** [comment]
Can you compare the average runtime of C++ and Python code? On our Jetson platform, the C++ feature extraction and matching is about  6x faster than the Python version. I think if a similar improvement can be achieved on your Jetson, we can conclude that Orin NX is actually not as good as AGX Xavier.

**Comment by Wu-ZW** [comment]
parameters:
max_keypoints:200
keypoint_threshold:0.004
match_threshold:0.1
Python (Pytorch-CUDA) Code:
Superpoint time: 0.10092282295227051
Superglue time: 0.10480713844299316
C++ TensorRT Code:
sp:adout 40 ms
sg:about 50 ms

**Comment by Wu-ZW** [comment]
In jeston Orin NX， the C++ feature extraction and matching is about 2x faster than the Python version. the improvement is not very obvious.

**Comment by xukuanHIT** [comment]
It's strange. I am not sure whether it is also caused by the TensorRT version. We have also encountered the efficiency problem when using TensorRT 8.5 on GeForce RTX GPUs that are lower than 40 series.  It is recommended to try to downgrade the driver version to 8.4.1.5 if possible.

**Comment by xukuanHIT** [comment]
May be similar this [issue](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/issues/32).

**Comment by Wu-ZW** [comment]
thanks a lot. I am also confused about above results. Addition, could I ask a question about how to export the PyTorch model to ONNX (int64)? I saw the scripts of convert_int32.py, is it convert INT64 to INT32 or FLOAT 32 to INT32?

**Comment by Wu-ZW** [comment]
> May be similar to this [issue](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/issues/32).
I doubt that "read image again", the same code runs normal on other platform.

**Comment by xukuanHIT** [comment]
> thanks a lot. I am also confused about above results. Addition, could I ask a question about how to export the PyTorch model to ONNX (int64)? I saw the scripts of convert_int32.py, is it convert INT64 to INT32 or FLOAT 32 to INT32?

Yes, just run the script.

**Comment by xukuanHIT** [comment]
> > May be similar to this [issue](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/issues/32).
> > I doubt that "read image again", the same code runs normal on other platform.

I mean the different environments may affect the runtime.
