### ISSUE TITLE
运行数据集出现进程异常结束

### ISSUE THREAD

**Issue by ljysimple** [sair-lab/AirSLAM#110]
WARN] [1718723053.486038178]: Pose 'Pose' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
roslaunch air_vo euroc_ros.launch 后在rviz上没有位姿、path等信息，只有image图像，图像中也没有线特征，不知道哪里出问题了

**Comment by xukuanHIT** [comment]
@ljysimple 抱歉这么晚回复。可以给出来一些程序的输出信息吗？

**Comment by xukuanHIT** [comment]
Since there has been no response for a long time, I will close this issue. Feel free to reopen it if needed.
