### ISSUE TITLE
where is voc file

### ISSUE THREAD

**Issue by liuguitao** [sair-lab/AirSLAM#120]
Thanks shared this project! It seems there should be have a voc folder,but I have'nt find it.

**Comment by liuguitao** [comment]
<img width="730" alt="voc" src="https://github.com/user-attachments/assets/471e4981-dc28-4cac-9e9b-df5465b874ff">

**Comment by xukuanHIT** [comment]
@liuguitao Hi, we just uploaded it [here](https://github.com/sair-lab/AirSLAM/tree/master/voc).

**Comment by liuguitao** [comment]
ok， thanks!
