### ISSUE TITLE
About the  [TABLE II] in the paper .    

### ISSUE THREAD

**Issue by GeYapeng** [sair-lab/AirSLAM#122]
Thank you for the great work of AirSLAM .
I'm a little confused when I read the paper . Here in the [TABLE II] when comparing with ORB-SLAM3 with loop , it shows the stereo-inertial(SI)  data of [0.036,  0.033,  0.035 ... ] , but marked with monocular-inertial(MI) .
There might be some misunderstanding .Which group of data should I refer to ? Could you please give me some advice ?
Looking forward to your reply ~

**Comment by xukuanHIT** [comment]
@GeYapeng Hi, thanks for the reminder. This should be the result for Stereo Inertial ORB-SLAM3. We've updated it in the paper, and the revised version will be released recently.

**Comment by GeYapeng** [comment]
Thanks !  Got it ~  \ >_< /
