### ISSUE TITLE
docker pull 一直报错。想问问大家是怎么pull下来的

### ISSUE THREAD

**Issue by 2805651606** [sair-lab/AirSLAM#129]

**Comment by xukuanHIT** [comment]
@2805651606 报什么错？网络问题？

**Comment by 2080524785** [comment]
You can choose to hook up an agent `sudo docker pull dockerproxy.cn/xukuanhit/air_slam:v4`

**Comment by 2080524785** [comment]
[https://dockerproxy.cn/](url)
这个网站可以加速
