### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by rangingwaves** [sair-lab/AirSLAM#131]
我使用的是一样的g2o版本，但是一直报CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
G2O_VIEWER_LIBRARY

**Comment by xukuanHIT** [comment]
@rangingwaves 你好，[这部分](https://github.com/RainerKuemmerle/g2o/tree/20230223_git#:~:text=Optional%20requirements)装了吗？或者在把[这个文件](https://github.com/sair-lab/AirSLAM/blob/master/cmake/FindG2O.cmake)的90、166行注释掉试试

**Comment by rangingwaves** [comment]
好的，谢谢。注释90、166行解决了。
