### ISSUE TITLE
About "FrameOptimization" in map_builder.cc

### ISSUE THREAD

**Issue by liwenlon** [sair-lab/AirSLAM#136]
I found that you write " FrameOptimization“ in the " MapBuilder  ".   However, you defined the line constraint, as "    MapOfLine3d lines;  ". But I noticed that you haven't assigned any line constraints. Did your line constraint work in the FrameOptimization function.   Please look line 323 and line 393 in "map_builder .cc  "  .
If I was wrong，please tell me what constraints did you add during real-time positioning.

**Comment by xukuanHIT** [comment]
@liwenlon Hi, line features are detected on keyframes, and used in local BA, global BA, and relocalization. They are not used in FrameOptimization.
