### ISSUE TITLE
AirSLAM vs RTAB-Map

### ISSUE THREAD

**Issue by wattanakorn495** [sair-lab/AirSLAM#144]
Hello, Thank you for developing this amazing project I'm new to the field of SLAM and currently trying to understand the differences between various algorithms. Could you explain what advantages your algorithm has over RTAB-Map?

**Comment by xukuanHIT** [comment]
@wattanakorn495 Hi, our advantages:
1. We utilize both point and line features for mapping and relocalization, whereas Rtab-Map only uses point features.
2. While Rtab-Map includes a module for handling long-term illumination changes, it first builds the map using traditional algorithms and only extracts learning-based features during offline processing for long-term localization. Therefore, it does not address the challenges posed by complex lighting conditions during mapping.
Our system's drawbacks:
1. A GPU is required, as there is no option for traditional feature extraction.
2. Currently, our integration with ROS is not as seamless as Rtab-Map's.

It is recommended to first read the papers of both systems and then choose the one that best suits your application.
