### ISSUE TITLE
LoopDetection bug

### ISSUE THREAD

**Issue by wattanakorn495** [sair-lab/AirSLAM#150]
Datatype should be double

`int loop_distance_thr = odometry_length * 0.03;`

`double loop_distance_thr = odometry_length * 0.03;`

and Should scale factor 0.03 be in config file?

**Comment by xukuanHIT** [comment]
@wattanakorn495 Hi, thank you for pointing out this bug; we have already fixed it. There are many parameters in the code, and we only provided a good initial value, which can indeed be modified based on the actual scenario. We are also considering adding them to the configuration file.
