### ISSUE TITLE
docker环境中onnx无法转换为engine

### ISSUE THREAD

**Issue by ZYL-0916** [sair-lab/AirSLAM#151]
![image](https://github.com/user-attachments/assets/d7b404f0-a715-4047-9038-83d84c9342cd)
在docker环境中roslaunch  air_slam vo_euroc.launch后rviz界面空白，之后发现onxx未正常生成engine，应该是builder创建失败
![image](https://github.com/user-attachments/assets/7b7f1530-d6bc-4ff2-a67f-0d274a8912b4)

**Comment by ZYL-0916** [comment]
主机nvidiv驱动版本低，更新后解决

**Comment by liangsongLee** [comment]
> Reference in new issue
@ZYL-0916 请问你的驱动更新到哪个版本？
