### ISSUE TITLE
fatal error: NvInferRuntimeCommon.h

### ISSUE THREAD

**Issue by Lmy971109** [sair-lab/AirSLAM#157]
Dear author, thank you for your important contribution. When I tried to configure the environment, the following problems occurred, which troubled me for a long time. Do you know what the reason is?
![image](https://github.com/user-attachments/assets/61932435-6c5b-4149-9b66-74c98794d69c)

**Comment by AlexWanghaoming** [comment]
Hi, have you solved this question? I met the same error as you did.
