### ISSUE TITLE
精度很高， 请问能否导出plnet的onnx的opset 12版本，目前是opset是17。能否提供原始的pth模型

### ISSUE THREAD

**Issue by xiongmao-cell** [sair-lab/AirSLAM#158]
您好，工程很好，代码很清晰，精度也高， 请问能否提供plnet的原始模式，  方便导出onnx opset的12版本，谢谢

**Comment by xukuanHIT** [comment]
@xiongmao-cell 你好，PLNet相关的python代码会在论文被接收时开源

**Comment by rendebin** [comment]
您好，请问您成功导出plnet的onnx模型了吗？能否提供plnet导出onnx的代码？万分感谢！

**Comment by ynma-hanvo** [comment]
plnet现在开源了吗
