### ISSUE TITLE
“No Image”

### ISSUE THREAD

**Issue by Lmy971109** [sair-lab/AirSLAM#159]
Dear author, thank you for your great contribution. However, after compiling, I executed "roslaunch air_slam vo_euroc.launch" but there was no data. The running results are as follows. What is the reason? I also used the data of EUROC V1_02_medium.
And the settings in vo_euroc.launch are as follows: 
![image](https://github.com/user-attachments/assets/ab099564-dea6-4e9f-bfac-fda5f144327c)

![image](https://github.com/user-attachments/assets/9cc4fcc7-1c4b-4dc2-9b7f-a0091b33dc69)

**Comment by zhanghanduo** [comment]
@Lmy971109 Hi. Did you resolve this issue? I also met the same problem without TensorRT running

**Comment by WuQi-Dancer** [comment]
> Dear author, thank you for your great contribution. However, after compiling, I executed "roslaunch air_slam vo_euroc.launch" but there was no data. The running results are as follows. What is the reason? I also used the data of EUROC V1_02_medium. And the settings in vo_euroc.launch are as follows: ![image](https://github.com/user-attachments/assets/ab099564-dea6-4e9f-bfac-fda5f144327c)
> 
> ![image](https://github.com/user-attachments/assets/9cc4fcc7-1c4b-4dc2-9b7f-a0091b33dc69)

Have you solved this problem?

**Comment by DevRookiee** [comment]
The same question I want to ask!!!

**Comment by luohongk** [comment]
The same question I want to ask!!!
