### ISSUE TITLE
你好，可以提供一下oivio数据集吗？官方的链接已经挂了

### ISSUE THREAD

**Issue by sukaixiong** [sair-lab/AirSLAM#167]
如果可以的话请发一下2656419064@qq.com，十分感谢

**Comment by xukuanHIT** [comment]
@sukaixiong https://entuedu-my.sharepoint.com/personal/kuan_xu_staff_main_ntu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fkuan%5Fxu%5Fstaff%5Fmain%5Fntu%5Fedu%5Fsg%2FDocuments%2Fdatasets%2Foivio&amp;ga=1
