### ISSUE TITLE
NX Jetpack版本

### ISSUE THREAD

**Issue by tomliuli** [sair-lab/AirSLAM#170]
您好，请问您在 Nvidia Jetson Orin 上的开发环境如何，是Jetpack6.0吗，ubuntu是20.04吗

**Comment by xukuanHIT** [comment]
是的

**Comment by tomliuli** [comment]
好的，感谢，但是jetpack不是对应ubuntu22.04吗，不是只能使用ros2吗

**Comment by xukuanHIT** [comment]
> jetpack6.0确实对应ubuntu22.04，但是ROS1可以源码编

@tomliuli 是的，源码安装的ros1，参照的这个[教程](https://gist.github.com/Meltwin/fe2c15a5d7e6a8795911907f627255e0)
