### ISSUE TITLE
OIVIO dataset 下载不了

### ISSUE THREAD

**Issue by Xie-HIT** [sair-lab/AirSLAM#175]
官方 OIVIO dataset 的链接挂了，能否发一份百度网盘的链接，谢谢了

**Comment by xukuanHIT** [comment]
#167

**Comment by sukaixiong** [comment]
> 官方 OIVIO dataset 的链接挂了，能否发一份百度网盘的链接，谢谢了

你能下吗？

**Comment by Xie-HIT** [comment]
谢谢回复，这个链接我试过了，但是如下图所示还是不能下
![截图](https://github.com/user-attachments/assets/c77eeff9-c246-46ae-91b4-fa1686c7a762)

**Comment by xukuanHIT** [comment]
https://entuedu-my.sharepoint.com/:f:/g/personal/kuan_xu_staff_main_ntu_edu_sg/EtabKNOPBPBMmjJXbN4A8wMB0MTZmeZlnfAi7bskgfAr7A?e=k62L8q ,可以试试这个链接

**Comment by Xie-HIT** [comment]
谢谢，这个链接可以下啦!
