### ISSUE TITLE
UMA-VI评估

### ISSUE THREAD

**Issue by xixishui1999** [sair-lab/AirSLAM#177]
作者您好，我在尝试评估AirVO的时候碰到了问题。我先用[rosbagCreator.py](https://github.com/dzunigan/uma_vi_tools/blob/master/python/rosbagCreator.py)将UMA-VI数据集转成了bag包，然后运行并保存airvo轨迹，之后使用UMA-VI官方提供的evaluate.py文件进行评估，但是“Translational alignment error RMSE:”会比较大，没有论文中效果，请问是评估方法不准确吗？是否和airvo的输出频率有关，我这边的/AirVO/odometry的输出频率只有1-3Hz。谢谢。

**Comment by xukuanHIT** [comment]
你好，我们直接用的EVO算得RMSE。我们没试过提供的evaluate.py，不确定它是不是像EVO一样，计算的是轨迹对齐后的RMSE？

**Comment by xixishui1999** [comment]
和EVO好像不太一样，因为这个数据集只提供了首尾的真值，在对应的论文中作者提到了如何进行轨迹对齐计算误差，并提供了评估脚本。
如果我使用EVO评估的话有什么地方需要注意的吗，直接将airvo输出的tum格式轨迹和首尾的真值轨迹利用evo_ape tum -a评估吗，还是需要对首尾分开处理，感谢您的回复。

**Comment by xukuanHIT** [comment]
对，我们直接用的evo_ape tum -a，这里不要加-s对齐尺度

**Comment by xixishui1999** [comment]
好的， 谢谢
